//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> dtDueDate { get; set; }
        public string sPriority { get; set; }
        public string sText { get; set; }
        public Nullable<int> iUserID { get; set; }
        public Nullable<bool> bComplete { get; set; }
    }
}
