//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int iUserID { get; set; }
        public string sUserName { get; set; }
        public string sMail { get; set; }
    }
}
